### ISSUE TITLE
user guide as .md? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/allenCCF#17]
@philshams: @jjlee42 has suggested making the user guide into a .md file in this repository rather than pdf. I guess the suggestion is so that it can be jointly maintained, e.g. if she figures out how to do something that wasn't clearly explained, she can just update it to be clearer directly. Correct @jjlee42 ?

**Comment by nsteinme** [comment]
also an option is to use the 'wiki' portion of this repository

**Comment by philshams** [comment]
I think using the wiki function is best, so it's both collaborative and well organized

**Comment by philshams** [comment]
Wiki first draft completed. Feel free to make things in it clearer.
