### ISSUE TITLE
error in Navigating in the AltasTransformBrowser

### ISSUE THREAD

**Issue by JulienCat** [cortex-lab/allenCCF#19]
In order to use Sharp track on some of my Nissl Slices, 
I have been following the wiki (https://github.com/cortex-lab/allenCCF/wiki)  
and it works until 'step3: Navigating in the reference atlas': "Navigating in the AltasTransformBrowser" 
it plot 2 blank figures: Figure 1: Atlas Viewer and Figure 2: Slice Viewer
and it return me the following error:  
```
Array indices must be positive integers or logical values.

Error in natsortfiles (line 135)
vec{numel(len)} = [];

Error in sliceBrowser (line 8)
ud_slice.processed_image_names = natsortfiles({processed_images.name});

Error in Navigate_Atlas_and_Register_Slices (line 39)
sliceBrowser(slice_figure_browser, processed_images_folder, f, reference_size);
```

notice that the simpler version, which does not interface with processed slice images, 
give me a non-blank figure with an image from the Atlas, when I uncomment the following: 
`% f = allenAtlasBrowser(tv,av,st, save_location, probe_save_name_suffix);`

**Comment by philshams** [comment]
In case this is still relevant: this error will occur when the processed_images_folder does not exist or does not contain any images. So first ensure that this folder was created and filled with slice images after going through the pre-processing steps. Then, assign the name of this newly created folder (e.g. _'C:\Drive\xold\Histology\SS096\processed'_) to the processed_images_folder variable, and it should work.
