### ISSUE TITLE
Determining position of ROI points

### ISSUE THREAD

**Issue by AjitRanganath** [cortex-lab/allenCCF#21]
Once I use Analyze_Clicked_Points, I get a table with the brain areas where my clicked points reside. How do I correlate the entries in the table with my clicked points?

The table just provides the brain areas the clicks were found in, abbreviations and coordinates. Do I need to use the av index to find which entries of the table correspond to my clicked points?

Thanks for the great tool!

**Comment by philshams** [comment]
I'm not sure what you mean by 'correlate the entries in the table with my clicked points'. Each entry in the table corresponds to a clicked point. They are listed in the order that you clicked them, for each probe. The av index is just the Allen Atlas index corresponding to the brain region where the clicked point resides. 

If you want to do any further analysis on them, you can use the _roi_location_ and _roi_annotation_ cell arrays. If you want to visualize them, you can use _Display_Probe_Track.m_.
