### ISSUE TITLE
Additional brain templates

### ISSUE THREAD

**Issue by Yawende** [cortex-lab/allenCCF#35]
Hi,

Thanks again for creating this tool, it is working great for me.
However, I was wondering if it would be possible to have other brain templates instead of the wireframe/braingrid? for instance a see trough brain in which you can highlight different brain areas.

The https://github.com/AllenInstitute/cocoframer package has this option but is coded in R and cannot indicate probe points in the 3D brain.

an example that I would like to use would be something like this...
![brain_demo2](https://user-images.githubusercontent.com/55844013/66402591-5c7d2a00-e9e5-11e9-9b1e-59c19d57ff6e.gif)
 
I understand if it is to much to ask.

kind regards,

Yawende

**Comment by petersaj** [comment]
Hi Yawende - allen_ccf_npx included with this repo does a version of that
(if you press plus/shift-plus it brings up the list of structures, then
clicking on one or more of them draws their semi-transparent outlines). If
you're interested in combining this with your aligned histology, you can
load probe points by clicking 'h' and then choosing the file with the saved
points. Apologies there isn't much documentation for this yet, let me know
if you use this and anything's not clear,

Andy
