### ISSUE TITLE
suggestions for process histology

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/allenCCF#6]
@philshams 

if we end up using this a lot more, here is a list of ideas, feel free to add stuff. just to keep track of things - don't need to implement immediately. 

- [x] convert to a handle/gui based method so crashes don't reset things, and matlab isn't stuck

- [x] separate identifying ROIs from rotate/sharpen; combine rotate/sharpen with the flipping/ordering
- [x] automatically show grid and sharpen twice (in my experience these are both always helpful)
- [x] auto-save transforms when created. 
- [x] system for file naming that maintains self-consistency if something crashes and you have to restart (I get _1_1, _1_2, _1_3... but then _2_1 when I had to restart in between them). also the images come out out-of-order when >10, i.e. _1_11 appears earlier than _1_2 in the list. 
recommendation: 
`[save_file_name num2str(slideNum,'%.2d') '_' num2str(imageNum,'%.3d') '.tif']`
- [x] faster rotation
- [x] make things un-do-able, able to step backwards
- [x] for contrast adjustment, show a histogram and allow adjustment of min/max there instead (I find it very hard to tell what's going on when using the scroll method with no indication of what's changing)

**Comment by philshams** [comment]
agreed

**Comment by philshams** [comment]
Done, in /philshams/philip -- will be added in next update
