### ISSUE TITLE
getting CCF data required for NTE

### ISSUE THREAD

**Issue by cyjzheng** [cortex-lab/allenCCF#68]
The link (http://data.cortexlab.net/allenCCF/) in README to get CCF data requires access. To work around, one out of 3 required files for Neuropixels Trajectory Explorer is in this repo (`structure_tree_safe_2017.csv`). To get the other two, I had to download `annotation_10.nrrd` and  `average_template_10.nrrd` using the link in `setup_utils.m` 2) convert those two `.nrrd` files to `.npy`.  

`setup_utils.m` in this rep does have a section 'convert annotation volume to index version' to covert 'annotation_10.nrrd'  to `annotation_volume_10um_by_index.npy`, however, it's not clear how to get  `template_volume_10um.npy` (also required for NTE).  

Turns out that the same section can be used to convert `average_template_10.nrrd` to `template_volume_10um.npy` just by changing the file name...  Hopefully this is helpful for those also confused at first like me. And it would be great if some explanations/comments can be added to `setup_utils.m`

**Comment by petersaj** [comment]
It looks like that link has started denying access, I've put the CCF into a different site which will be permanently available for download: https://osf.io/fv7ed/

Those files then shouldn't need any setup and should work as-is, I'll close the issue but let me know if you run into problems.
