### ISSUE TITLE
unable to open link to 4 files of AllenCCF tools

### ISSUE THREAD

**Issue by c-t-m95** [cortex-lab/allenCCF#73]
link broken to Allen atlas files needed to download

**Comment by jeongjunjjkim** [comment]
Seconding this issue - the link is completely broken

**Comment by nsteinme** [comment]
thanks for raising this - I have now uploaded the files to a new location and updated the readme accordingly (they are here: https://dx.doi.org/10.6084/m9.figshare.25365829).
